AI_pos.add((4,4))
    AI_pos.add((4,6))
    AI_pos.add((3,5))
    AI_pos.add((2,4))
    AI_pos.add((5,6))
    AI_pos.add((9,1))
    AI_pos.add((2,6))
    AI_pos.add((8,5))
    AI_pos.add((1,7))
    # AI_pos.add((3,6))

    Man_pos.add((5,5))
    Man_pos.add((6,4))
    Man_pos.add((4,5))
    Man_pos.add((7,3))
    Man_pos.add((5,7))
    Man_pos.add((8,2))
    Man_pos.add((7,5))
    Man_pos.add((6,5))
    Man_pos.add((6,6))
    Man_pos.add((5,3))