# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DirectoryServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DirectoryServer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x44irectoryServer.proto\"\x1c\n\tDir_Reply\x12\x0f\n\x07success\x18\x01 \x01(\x05\"\x1a\n\tDir_Empty\x12\r\n\x05\x65mpty\x18\x01 \x01(\x05\"N\n\rFileServer_On\x12\x11\n\tServer_ID\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\"#\n\x0e\x46ileServer_Off\x12\x11\n\tServer_ID\x18\x01 \x01(\x05\"P\n\x0f\x46ileServer_info\x12\x11\n\tServer_ID\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\"8\n\x0f\x46ileServer_List\x12%\n\x0bserver_list\x18\x01 \x03(\x0b\x32\x10.FileServer_info2\xa4\x01\n\tDirServer\x12\x31\n\x11\x66ileserver_online\x12\x0e.FileServer_On\x1a\n.Dir_Reply\"\x00\x12\x33\n\x12\x66ileserver_offline\x12\x0f.FileServer_Off\x1a\n.Dir_Reply\"\x00\x12/\n\rgetfileserver\x12\n.Dir_Empty\x1a\x10.FileServer_List\"\x00\x62\x06proto3')
)




_DIR_REPLY = _descriptor.Descriptor(
  name='Dir_Reply',
  full_name='Dir_Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Dir_Reply.success', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=53,
)


_DIR_EMPTY = _descriptor.Descriptor(
  name='Dir_Empty',
  full_name='Dir_Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='empty', full_name='Dir_Empty.empty', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=81,
)


_FILESERVER_ON = _descriptor.Descriptor(
  name='FileServer_On',
  full_name='FileServer_On',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Server_ID', full_name='FileServer_On.Server_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='FileServer_On.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='FileServer_On.port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='FileServer_On.location', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=161,
)


_FILESERVER_OFF = _descriptor.Descriptor(
  name='FileServer_Off',
  full_name='FileServer_Off',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Server_ID', full_name='FileServer_Off.Server_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=198,
)


_FILESERVER_INFO = _descriptor.Descriptor(
  name='FileServer_info',
  full_name='FileServer_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Server_ID', full_name='FileServer_info.Server_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='FileServer_info.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='FileServer_info.port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='FileServer_info.location', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=280,
)


_FILESERVER_LIST = _descriptor.Descriptor(
  name='FileServer_List',
  full_name='FileServer_List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_list', full_name='FileServer_List.server_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=338,
)

_FILESERVER_LIST.fields_by_name['server_list'].message_type = _FILESERVER_INFO
DESCRIPTOR.message_types_by_name['Dir_Reply'] = _DIR_REPLY
DESCRIPTOR.message_types_by_name['Dir_Empty'] = _DIR_EMPTY
DESCRIPTOR.message_types_by_name['FileServer_On'] = _FILESERVER_ON
DESCRIPTOR.message_types_by_name['FileServer_Off'] = _FILESERVER_OFF
DESCRIPTOR.message_types_by_name['FileServer_info'] = _FILESERVER_INFO
DESCRIPTOR.message_types_by_name['FileServer_List'] = _FILESERVER_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dir_Reply = _reflection.GeneratedProtocolMessageType('Dir_Reply', (_message.Message,), {
  'DESCRIPTOR' : _DIR_REPLY,
  '__module__' : 'DirectoryServer_pb2'
  # @@protoc_insertion_point(class_scope:Dir_Reply)
  })
_sym_db.RegisterMessage(Dir_Reply)

Dir_Empty = _reflection.GeneratedProtocolMessageType('Dir_Empty', (_message.Message,), {
  'DESCRIPTOR' : _DIR_EMPTY,
  '__module__' : 'DirectoryServer_pb2'
  # @@protoc_insertion_point(class_scope:Dir_Empty)
  })
_sym_db.RegisterMessage(Dir_Empty)

FileServer_On = _reflection.GeneratedProtocolMessageType('FileServer_On', (_message.Message,), {
  'DESCRIPTOR' : _FILESERVER_ON,
  '__module__' : 'DirectoryServer_pb2'
  # @@protoc_insertion_point(class_scope:FileServer_On)
  })
_sym_db.RegisterMessage(FileServer_On)

FileServer_Off = _reflection.GeneratedProtocolMessageType('FileServer_Off', (_message.Message,), {
  'DESCRIPTOR' : _FILESERVER_OFF,
  '__module__' : 'DirectoryServer_pb2'
  # @@protoc_insertion_point(class_scope:FileServer_Off)
  })
_sym_db.RegisterMessage(FileServer_Off)

FileServer_info = _reflection.GeneratedProtocolMessageType('FileServer_info', (_message.Message,), {
  'DESCRIPTOR' : _FILESERVER_INFO,
  '__module__' : 'DirectoryServer_pb2'
  # @@protoc_insertion_point(class_scope:FileServer_info)
  })
_sym_db.RegisterMessage(FileServer_info)

FileServer_List = _reflection.GeneratedProtocolMessageType('FileServer_List', (_message.Message,), {
  'DESCRIPTOR' : _FILESERVER_LIST,
  '__module__' : 'DirectoryServer_pb2'
  # @@protoc_insertion_point(class_scope:FileServer_List)
  })
_sym_db.RegisterMessage(FileServer_List)



_DIRSERVER = _descriptor.ServiceDescriptor(
  name='DirServer',
  full_name='DirServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=341,
  serialized_end=505,
  methods=[
  _descriptor.MethodDescriptor(
    name='fileserver_online',
    full_name='DirServer.fileserver_online',
    index=0,
    containing_service=None,
    input_type=_FILESERVER_ON,
    output_type=_DIR_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='fileserver_offline',
    full_name='DirServer.fileserver_offline',
    index=1,
    containing_service=None,
    input_type=_FILESERVER_OFF,
    output_type=_DIR_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getfileserver',
    full_name='DirServer.getfileserver',
    index=2,
    containing_service=None,
    input_type=_DIR_EMPTY,
    output_type=_FILESERVER_LIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIRSERVER)

DESCRIPTOR.services_by_name['DirServer'] = _DIRSERVER

# @@protoc_insertion_point(module_scope)
