# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LockServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LockServer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10LockServer.proto\"\x1d\n\nLock_Reply\x12\x0f\n\x07success\x18\x01 \x01(\x05\"\x1b\n\nLock_Empty\x12\r\n\x05\x65mpty\x18\x01 \x01(\x05\"F\n\x0clockfileinfo\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"5\n\x0eunlockfileinfo\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t2d\n\nLockServer\x12(\n\x08lockfile\x12\r.lockfileinfo\x1a\x0b.Lock_Reply\"\x00\x12,\n\nunlockfile\x12\x0f.unlockfileinfo\x1a\x0b.Lock_Reply\"\x00\x62\x06proto3')
)




_LOCK_REPLY = _descriptor.Descriptor(
  name='Lock_Reply',
  full_name='Lock_Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Lock_Reply.success', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=49,
)


_LOCK_EMPTY = _descriptor.Descriptor(
  name='Lock_Empty',
  full_name='Lock_Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='empty', full_name='Lock_Empty.empty', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=78,
)


_LOCKFILEINFO = _descriptor.Descriptor(
  name='lockfileinfo',
  full_name='lockfileinfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='lockfileinfo.client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_path', full_name='lockfileinfo.file_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='lockfileinfo.filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=150,
)


_UNLOCKFILEINFO = _descriptor.Descriptor(
  name='unlockfileinfo',
  full_name='unlockfileinfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='unlockfileinfo.file_path', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='unlockfileinfo.filename', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['Lock_Reply'] = _LOCK_REPLY
DESCRIPTOR.message_types_by_name['Lock_Empty'] = _LOCK_EMPTY
DESCRIPTOR.message_types_by_name['lockfileinfo'] = _LOCKFILEINFO
DESCRIPTOR.message_types_by_name['unlockfileinfo'] = _UNLOCKFILEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lock_Reply = _reflection.GeneratedProtocolMessageType('Lock_Reply', (_message.Message,), {
  'DESCRIPTOR' : _LOCK_REPLY,
  '__module__' : 'LockServer_pb2'
  # @@protoc_insertion_point(class_scope:Lock_Reply)
  })
_sym_db.RegisterMessage(Lock_Reply)

Lock_Empty = _reflection.GeneratedProtocolMessageType('Lock_Empty', (_message.Message,), {
  'DESCRIPTOR' : _LOCK_EMPTY,
  '__module__' : 'LockServer_pb2'
  # @@protoc_insertion_point(class_scope:Lock_Empty)
  })
_sym_db.RegisterMessage(Lock_Empty)

lockfileinfo = _reflection.GeneratedProtocolMessageType('lockfileinfo', (_message.Message,), {
  'DESCRIPTOR' : _LOCKFILEINFO,
  '__module__' : 'LockServer_pb2'
  # @@protoc_insertion_point(class_scope:lockfileinfo)
  })
_sym_db.RegisterMessage(lockfileinfo)

unlockfileinfo = _reflection.GeneratedProtocolMessageType('unlockfileinfo', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKFILEINFO,
  '__module__' : 'LockServer_pb2'
  # @@protoc_insertion_point(class_scope:unlockfileinfo)
  })
_sym_db.RegisterMessage(unlockfileinfo)



_LOCKSERVER = _descriptor.ServiceDescriptor(
  name='LockServer',
  full_name='LockServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=207,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='lockfile',
    full_name='LockServer.lockfile',
    index=0,
    containing_service=None,
    input_type=_LOCKFILEINFO,
    output_type=_LOCK_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='unlockfile',
    full_name='LockServer.unlockfile',
    index=1,
    containing_service=None,
    input_type=_UNLOCKFILEINFO,
    output_type=_LOCK_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCKSERVER)

DESCRIPTOR.services_by_name['LockServer'] = _LOCKSERVER

# @@protoc_insertion_point(module_scope)
