# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FileServer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x46ileServer.proto\"\x17\n\x05\x43hunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x16\n\x05\x45mpty\x12\r\n\x05\x65mpty\x18\x01 \x01(\x05\"5\n\x0eUpload_Request\x12\x13\n\x0btarget_path\x18\x01 \x01(\t\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\")\n\x10\x44ownload_Request\x12\x15\n\rdownload_path\x18\x01 \x01(\t\"%\n\x0e\x44\x65lete_Request\x12\x13\n\x0b\x64\x65lete_path\x18\x01 \x01(\t\" \n\x0cList_Request\x12\x10\n\x08\x63ur_path\x18\x01 \x01(\t\"!\n\rMkdir_Request\x12\x10\n\x08\x64ir_path\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07success\x18\x01 \x01(\x05\"\x1a\n\nList_Reply\x12\x0c\n\x04list\x18\x01 \x01(\t\"\x18\n\tPWD_Reply\x12\x0b\n\x03pwd\x18\x01 \x01(\t2\xcd\x02\n\nFileServer\x12%\n\x06upload\x12\x0f.Upload_Request\x1a\x06.Reply\"\x00(\x01\x12\x31\n\x12upload_without_syn\x12\x0f.Upload_Request\x1a\x06.Reply\"\x00(\x01\x12)\n\x08\x64ownload\x12\x11.Download_Request\x1a\x06.Chunk\"\x00\x30\x01\x12#\n\x06\x64\x65lete\x12\x0f.Delete_Request\x1a\x06.Reply\"\x00\x12/\n\x12\x64\x65lete_without_syn\x12\x0f.Delete_Request\x1a\x06.Reply\"\x00\x12$\n\x04list\x12\r.List_Request\x1a\x0b.List_Reply\"\x00\x12\x1b\n\x03pwd\x12\x06.Empty\x1a\n.PWD_Reply\"\x00\x12!\n\x05mkdir\x12\x0e.Mkdir_Request\x1a\x06.Reply\"\x00\x62\x06proto3')
)




_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='Chunk.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=43,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='empty', full_name='Empty.empty', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=67,
)


_UPLOAD_REQUEST = _descriptor.Descriptor(
  name='Upload_Request',
  full_name='Upload_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_path', full_name='Upload_Request.target_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buffer', full_name='Upload_Request.buffer', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=122,
)


_DOWNLOAD_REQUEST = _descriptor.Descriptor(
  name='Download_Request',
  full_name='Download_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='download_path', full_name='Download_Request.download_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=165,
)


_DELETE_REQUEST = _descriptor.Descriptor(
  name='Delete_Request',
  full_name='Delete_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delete_path', full_name='Delete_Request.delete_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=204,
)


_LIST_REQUEST = _descriptor.Descriptor(
  name='List_Request',
  full_name='List_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cur_path', full_name='List_Request.cur_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=238,
)


_MKDIR_REQUEST = _descriptor.Descriptor(
  name='Mkdir_Request',
  full_name='Mkdir_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir_path', full_name='Mkdir_Request.dir_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=273,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Reply.success', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=299,
)


_LIST_REPLY = _descriptor.Descriptor(
  name='List_Reply',
  full_name='List_Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='List_Reply.list', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=327,
)


_PWD_REPLY = _descriptor.Descriptor(
  name='PWD_Reply',
  full_name='PWD_Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pwd', full_name='PWD_Reply.pwd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=353,
)

DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Upload_Request'] = _UPLOAD_REQUEST
DESCRIPTOR.message_types_by_name['Download_Request'] = _DOWNLOAD_REQUEST
DESCRIPTOR.message_types_by_name['Delete_Request'] = _DELETE_REQUEST
DESCRIPTOR.message_types_by_name['List_Request'] = _LIST_REQUEST
DESCRIPTOR.message_types_by_name['Mkdir_Request'] = _MKDIR_REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['List_Reply'] = _LIST_REPLY
DESCRIPTOR.message_types_by_name['PWD_Reply'] = _PWD_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:Chunk)
  })
_sym_db.RegisterMessage(Chunk)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Upload_Request = _reflection.GeneratedProtocolMessageType('Upload_Request', (_message.Message,), {
  'DESCRIPTOR' : _UPLOAD_REQUEST,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:Upload_Request)
  })
_sym_db.RegisterMessage(Upload_Request)

Download_Request = _reflection.GeneratedProtocolMessageType('Download_Request', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOAD_REQUEST,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:Download_Request)
  })
_sym_db.RegisterMessage(Download_Request)

Delete_Request = _reflection.GeneratedProtocolMessageType('Delete_Request', (_message.Message,), {
  'DESCRIPTOR' : _DELETE_REQUEST,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:Delete_Request)
  })
_sym_db.RegisterMessage(Delete_Request)

List_Request = _reflection.GeneratedProtocolMessageType('List_Request', (_message.Message,), {
  'DESCRIPTOR' : _LIST_REQUEST,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:List_Request)
  })
_sym_db.RegisterMessage(List_Request)

Mkdir_Request = _reflection.GeneratedProtocolMessageType('Mkdir_Request', (_message.Message,), {
  'DESCRIPTOR' : _MKDIR_REQUEST,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:Mkdir_Request)
  })
_sym_db.RegisterMessage(Mkdir_Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  })
_sym_db.RegisterMessage(Reply)

List_Reply = _reflection.GeneratedProtocolMessageType('List_Reply', (_message.Message,), {
  'DESCRIPTOR' : _LIST_REPLY,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:List_Reply)
  })
_sym_db.RegisterMessage(List_Reply)

PWD_Reply = _reflection.GeneratedProtocolMessageType('PWD_Reply', (_message.Message,), {
  'DESCRIPTOR' : _PWD_REPLY,
  '__module__' : 'FileServer_pb2'
  # @@protoc_insertion_point(class_scope:PWD_Reply)
  })
_sym_db.RegisterMessage(PWD_Reply)



_FILESERVER = _descriptor.ServiceDescriptor(
  name='FileServer',
  full_name='FileServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=356,
  serialized_end=689,
  methods=[
  _descriptor.MethodDescriptor(
    name='upload',
    full_name='FileServer.upload',
    index=0,
    containing_service=None,
    input_type=_UPLOAD_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='upload_without_syn',
    full_name='FileServer.upload_without_syn',
    index=1,
    containing_service=None,
    input_type=_UPLOAD_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='download',
    full_name='FileServer.download',
    index=2,
    containing_service=None,
    input_type=_DOWNLOAD_REQUEST,
    output_type=_CHUNK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='FileServer.delete',
    index=3,
    containing_service=None,
    input_type=_DELETE_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delete_without_syn',
    full_name='FileServer.delete_without_syn',
    index=4,
    containing_service=None,
    input_type=_DELETE_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='list',
    full_name='FileServer.list',
    index=5,
    containing_service=None,
    input_type=_LIST_REQUEST,
    output_type=_LIST_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pwd',
    full_name='FileServer.pwd',
    index=6,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PWD_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='mkdir',
    full_name='FileServer.mkdir',
    index=7,
    containing_service=None,
    input_type=_MKDIR_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESERVER)

DESCRIPTOR.services_by_name['FileServer'] = _FILESERVER

# @@protoc_insertion_point(module_scope)
